#!/bin/bash
cat << EOT >> ~/.bashrc
source /opt/ros/kinetic/setup.bash
#export ROS_MASTER_URI=http://192.168.65.2:11311
export ROS_HOSTNAME=192.168.65.2
export ROS_IP=192.168.65.2
EOT
echo "Almost there...."
sudo apt install -y ros-kinetic-rosapi ros-kinetic-rosauth libbson-dev python-bson iputils-ping >/dev/null 2>&1
echo "done!"
