#!/bin/bash
cat << EOT >> ~/.bashrc
source /opt/ros/indigo/setup.bash
#export ROS_MASTER_URI=http://192.168.65.3:11311
export ROS_HOSTNAME=192.168.65.3
export ROS_IP=192.168.65.3:11311
EOT
echo "Almost there...."
sudo apt install -y ros-indigo-rosapi ros-indigo-rosauth libbson-dev python-bson iputils-ping >/dev/null 2>&1
echo "done!"
