#!/bin/bash

USER_ID=$(id -u)
USERNAME=$(id -un)
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
IMAGE=rishabh880/ros-docker-trusty

#echo "Starting the socat docker forwarding for gui windows"
#socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\" &
echo "Starting the container"
sudo docker run -it --rm \
			--net=host \
        	  	 --pid=host \
          		 --privileged \
          		 -e USER_ID=${USER_ID} \
          		 -e USERNAME=${USERNAME} \
          		 -v ${XSOCK}:${XSOCK}:rw \
          		 -v ${XAUTH}:${XAUTH}:rw \
          		 -e XAUTHORITY=${XAUTH} \
        	  	 -e DISPLAY=192.168.65.2:0 \
          		 -v /Users/${USERNAME}:/mnt/host_home \
          		 --cap-add=ALL \
          		 --name ros-indigo-${USERNAME} \
          		 --expose=9090 \
			 rishabh880/ros-docker-trusty
